### ISSUE TITLE
Allow custom extensions

### ISSUE THREAD

**Issue by svenefftinge** [eclipselabs/eclipse-language-service#97]
A generic facility that just supports the standard LSP is a great basis for many cases. 
But in not too few cases it could be good to add language specific extensions. 

I think it would be good if I could register a standard Eclipse plugin where I would be responsible for setting up and connect to a language server and through that could register other extensions (like e.g. commands) to use the language server connection for additional things.

**Comment by mickaelistria** [comment]
Indeed, support for custom operations from external plugins is something that must be enabled. I see multiple complementary ways to do this:
- Have an extension point to let extenders register commands; or even better, reuse and consume the existing Eclipse commands/handlers mechanism to define commands on client side
- Open some classes of LSP4E as APIs so extenders could retrieve the LanguageServer connection to support custom operations

We'll need real-life example to guide us in taking the best decisions here.
I would really like the Language Server integration to be as much black-box as possible and to have ways to add support for a new server without writing any piece of code (that's more the topic of #96 );
And to open up as little things as possible, to guarantee some level of consistency but also to encourage innovation to happen in the protocol directly rather than having a lot of client/language-specific stuff in all clients/language servers; in which case it will really diminish the value of the protocol on the long run.

**Comment by svenefftinge** [comment]
My motivation wasn't to have common things that are not yet covered in LSP, but to allow for very language specific functionality that is supported by the language server through custom messages.
Therefore +1 on allowing extenders access to a language server endpoint.

**Comment by mickaelistria** [comment]
Replaced with https://bugs.eclipse.org/bugs/show_bug.cgi?id=508484
